call plug#begin('~/.vim/plugged')
    Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
    Plug 'junegunn/goyo.vim',
    Plug 'rust-lang/rust.vim',
    Plug 'dense-analysis/ale',
    Plug 'rstacruz/vim-closer',
    Plug 'terryma/vim-expand-region',
    Plug 'vimwiki/vimwiki',
    Plug 'Shougo/deoplete.nvim',
    Plug 'vim-scripts/AutoComplPop'
call plug#end()

nnoremap <Space>r :source ~/.config/vim/vimrc<CR>
nnoremap <esc>^[ <esc>^[

set cul
hi CursorLine   cterm=NONE ctermbg=black ctermfg=NONE

syntax enable
set nocompatible
set tabstop=3
set shiftwidth=3
set expandtab     
set smarttab      
set title

set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0
highlight lCursor guifg=NONE guibg=Cyan
source ~/.config/vim/ruscmd.vim

set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯЖ;ABCDEFGHIJKLMNOPQRSTUVWXYZ:,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

nmap <Space>i :!compile % &<CR>
nmap <Space>ш :!compile % &<CR>

nnoremap j gj
nnoremap k gk
nnoremap H 0
nnoremap L A
nmap K <Plug>(expand_region_expand)
nmap J <Plug>(expand_region_shrink)
nnoremap <silent> <esc> <esc>:noh<cr>
nnoremap <Space>a :ALEToggle<CR>

let g:ale_lint_on_text_changed = 'never'
let g:ale_completion_enabled = 1
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
call deoplete#custom#option('sources', {
         \ '_': ['ale'],
         \})
filetype plugin on
set omnifunc=ale#completion#OmniFunc
let g:ale_completion_autoimport = 1
set complete+=kspell
set completeopt=menuone,longest
set shortmess+=c
inoremap <expr> <Tab> pumvisible() ? "<C-y>" :"<Tab>"

inoremap <F6> set spelllang=ru \ 
   set spell!
inoremap <F7> set spelllang=en_us \ 
   set spell!

ab llp <Esc>/<++><Enter>df>i
ab llul \begin{itemize}<Enter><Enter><Enter><Enter>\end{itemize}<Esc>kki<Tab>\item
ab llol \begin{numerize}<Enter><Enter><Enter><Enter>\end{numerize}<Esc>kki<Tab>\item
ab llb \textbf{}<Esc>i
ab lli \textit{}<Esc>i
ab llsl \textsl{}<Esc>i
ab llrm \textrm{}<Esc>i
ab llsf \textsf{}<Esc>i
ab lltt \texttt{}<Esc>i
ab llsc \textsc{}<Esc>i
ab llnc \newcommand
ab llmt \maketitle
ab lldc \documentclass<Esc>i
ab llup \usepackage<Esc>i
ab llcenter \begin{center}<Enter><Enter><Enter>\end{center}<Esc>ki
ab llsec \section{}<Esc>i
ab llsubsec \subsection{}<Esc>i
ab llsubsubsec \subsubsection{}<Esc>i
ab llpar \paragraph
ab llsubpar \subparagraph

ab htol <ol><Enter><Enter></ol><Esc>ki
ab htul <ul><Enter><Enter></ul><Esc>ki
ab htli <li></li><Esc>F<i
ab htmlp <!DOCTYPE html><Enter><html><Enter><head><Enter><meta charset="utf-8"/><Enter><meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes"/><Enter><title><++></title><Enter><link rel="stylesheet" href="style.css"/><Enter></head><Enter><body><Enter><++><Enter></body><Enter><Esc>d0i</html><Esc>gg/<++><Enter>df>i
ab htp <p></p><Esc>F<i
