#!/bin/sh

delim='・'

disks() {
    df -h \
        | grep "sda$1" \
        | awk '{print $4}'
}

update() {
    pacman -Qu | wc -l 
}

memory() {
    free --mebi \
        | sed -n '2{p;q}' \
        | awk '{printf ("%2.2fGiB/%2.2fGiB\n", ($3/1024), ($2/1024))}'
}

currency() {
   URL=https://www.cbr-xml-daily.ru/daily_json.js
   curl $URL | jq '.Valute.USD.Value' | awk '{printf("%.1f", $1)}'
}

while true; do
   xsetroot -name "USD: $(currency) $delim upd: $(update) $delim $(memory) $delim sda4: $(disks 4) $delim sda3: $(disks 3) $delim $(date)"
    sleep 4
done
