#!/bin/sh

delim='・'

disks() {
    df -h \
        | grep "sd$1" \
        | awk '{print $4}'
}

update() {
    pacman -Qu | wc -l 
}

memory() {
    free --mebi \
        | sed -n '2{p;q}' \
        | awk '{printf ("%2.2fGiB/%2.2fGiB\n", ($3/1024), ($2/1024))}'
}

currency() {
   URL=https://www.cbr-xml-daily.ru/daily_json.js
   curl --connect-timeout 2 -sf $URL | jq '.Valute.USD.Value' | awk '{printf("%.1f", $1)}' || echo "no_currency"
}

while true; do
   xsetroot -name "Weather:$(forecast) $delim USD: $(currency) $delim $(memory) $delim OS: $(disks a1) $delim files: $(disks b1) $delim $(date)"
    sleep 4
done
