#!/bin/sh
# formats cmus-remote -Q in nice way
cmus-remote -Q \
   | grep -e ' artist' -e 'title' -e 'date' -e 'status' \
   | sed '
      s/tag //g; 
      s/artist //g; 
      s/title /- /; 
      /status/s/^.*/&: /;
      s/status //g;
      /date/s/^.*/(&)/; s/date //; 
      s/\s$//g' \
   | tr '\n' ' '
